package com.ccas.models.entities;
// Generated May 29, 2015 10:57:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customercategory generated by hbm2java
 */
public class Customercategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set advertisements = new HashSet(0);
     private Set properties = new HashSet(0);

    public Customercategory() {
    }

	
    public Customercategory(String name) {
        this.name = name;
    }
    public Customercategory(String name, Set advertisements, Set properties) {
       this.name = name;
       this.advertisements = advertisements;
       this.properties = properties;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAdvertisements() {
        return this.advertisements;
    }
    
    public void setAdvertisements(Set advertisements) {
        this.advertisements = advertisements;
    }
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }




}


