package com.ccas.models.entities;
// Generated May 29, 2015 10:57:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private Integer id;
     private Boolean addUser;
     private Boolean editUser;
     private Boolean deleteUser;
     private Boolean addAds;
     private Boolean editAds;
     private Boolean removeAds;
     private Boolean addCategories;
     private Boolean editCategories;
     private Boolean removeCategories;
     private Boolean manageRoles;
     private Set roles = new HashSet(0);

    public Privilege() {
    }

    public Privilege(Boolean addUser, Boolean editUser, Boolean deleteUser, Boolean addAds, Boolean editAds, Boolean removeAds, Boolean addCategories, Boolean editCategories, Boolean removeCategories, Boolean manageRoles, Set roles) {
       this.addUser = addUser;
       this.editUser = editUser;
       this.deleteUser = deleteUser;
       this.addAds = addAds;
       this.editAds = editAds;
       this.removeAds = removeAds;
       this.addCategories = addCategories;
       this.editCategories = editCategories;
       this.removeCategories = removeCategories;
       this.manageRoles = manageRoles;
       this.roles = roles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Boolean getAddUser() {
        return this.addUser;
    }
    
    public void setAddUser(Boolean addUser) {
        this.addUser = addUser;
    }
    public Boolean getEditUser() {
        return this.editUser;
    }
    
    public void setEditUser(Boolean editUser) {
        this.editUser = editUser;
    }
    public Boolean getDeleteUser() {
        return this.deleteUser;
    }
    
    public void setDeleteUser(Boolean deleteUser) {
        this.deleteUser = deleteUser;
    }
    public Boolean getAddAds() {
        return this.addAds;
    }
    
    public void setAddAds(Boolean addAds) {
        this.addAds = addAds;
    }
    public Boolean getEditAds() {
        return this.editAds;
    }
    
    public void setEditAds(Boolean editAds) {
        this.editAds = editAds;
    }
    public Boolean getRemoveAds() {
        return this.removeAds;
    }
    
    public void setRemoveAds(Boolean removeAds) {
        this.removeAds = removeAds;
    }
    public Boolean getAddCategories() {
        return this.addCategories;
    }
    
    public void setAddCategories(Boolean addCategories) {
        this.addCategories = addCategories;
    }
    public Boolean getEditCategories() {
        return this.editCategories;
    }
    
    public void setEditCategories(Boolean editCategories) {
        this.editCategories = editCategories;
    }
    public Boolean getRemoveCategories() {
        return this.removeCategories;
    }
    
    public void setRemoveCategories(Boolean removeCategories) {
        this.removeCategories = removeCategories;
    }
    public Boolean getManageRoles() {
        return this.manageRoles;
    }
    
    public void setManageRoles(Boolean manageRoles) {
        this.manageRoles = manageRoles;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


