package com.ccas.models.entities;
// Generated May 29, 2015 10:57:01 PM by Hibernate Tools 4.3.1



/**
 * Property generated by hbm2java
 */
public class Property  implements java.io.Serializable {


     private Integer id;
     private Customercategory customercategory;
     private String name;
     private String value;

    public Property() {
    }

    public Property(Customercategory customercategory, String name, String value) {
       this.customercategory = customercategory;
       this.name = name;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customercategory getCustomercategory() {
        return this.customercategory;
    }
    
    public void setCustomercategory(Customercategory customercategory) {
        this.customercategory = customercategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


