package com.ccas.models.entities;
// Generated May 29, 2015 10:57:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private Privilege privilege;
     private String name;
     private Set users = new HashSet(0);

    public Role() {
    }

	
    public Role(Privilege privilege, String name) {
        this.privilege = privilege;
        this.name = name;
    }
    public Role(Privilege privilege, String name, Set users) {
       this.privilege = privilege;
       this.name = name;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


